CREATE TABLE "bus" (
  "bus_id" uuid PRIMARY KEY,
  "carplate" varchar,
  "status" boolean NOT NULL,
  "hidden" boolean
);

CREATE TABLE "stop" (
  "stop_name" varchar PRIMARY KEY,
  "lng" float,
  "lat" float
);

CREATE TABLE "route" (
  "route_name" varchar PRIMARY KEY,
  "color" varchar
);

CREATE TABLE "route_step" (
  "route_name" varchar,
  "stop_name" varchar,
  "order" int NOT NULL,
  PRIMARY KEY ("route_name", "stop_name")
);

CREATE TABLE "driver" (
  "driver_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "driver_name" varchar NOT NULL
);

CREATE TABLE "bus_schedule" (
  "bus_schedule_id" INT GENERATED BY DEFAULT AS IDENTITY,
  "bus_id" uuid,
  "route_name" varchar,
  "driver_id" int,
  "start_time" timestamptz,
  "end_time" timestamptz,
  PRIMARY KEY ("bus_schedule_id", "bus_id", "route_name", "driver_id", "start_time", "end_time")
);

CREATE TABLE "event_type" (
  "event_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_name" varchar NOT NULL
);

CREATE TABLE "user_role" (
  "role_id" int PRIMARY KEY,
  "role_name" varchar NOT NULL
);

CREATE TABLE "user_table" (
  "email" varchar PRIMARY KEY,
  "name" varchar NOT NULL,
  "password" varchar NOT NULL,
  "role_id" int NOT NULL,
  "verification_token" varchar,
  "contact" varchar
);

CREATE TABLE "event" (
  "timestamp" timestamptz,
  "bus_id" uuid,
  "route_name" varchar,
  "event_id" int,
  "stop_name" varchar,
  PRIMARY KEY ("timestamp", "bus_id", "route_name", "event_id", "stop_name")
);

CREATE TABLE "event_helper" (
  "bus_id" uuid,
  "email" varchar,
  "shift" boolean,
  PRIMARY KEY ("bus_id", "email")
);

CREATE TABLE "chat_room" (
  "room_id" uuid,
  "email" varchar,
  PRIMARY KEY ("room_id", "email")
);

CREATE TABLE "room_name" (
  "room_id" uuid PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "chat_message" (
  "timestamp" timestamptz,
  "from" varchar,
  "room_id" uuid,
  "body" varchar,
  PRIMARY KEY ("timestamp", "from", "room_id")
);

CREATE TABLE "swap_request" (
  "from" varchar,
  "with" varchar,
  "timestamp" timestamp,
  "accepted" bool,
  PRIMARY KEY ("from", "with", "timestamp")
);

CREATE TABLE "past_passwords" (
  "email" varchar,
  "password" varchar,
  PRIMARY KEY ("email", "password")
);

ALTER TABLE "event" ADD FOREIGN KEY ("bus_id") REFERENCES "bus" ("bus_id");

ALTER TABLE "event" ADD FOREIGN KEY ("route_name") REFERENCES "route" ("route_name");

ALTER TABLE "event" ADD FOREIGN KEY ("event_id") REFERENCES "event_type" ("event_id");

ALTER TABLE "event" ADD FOREIGN KEY ("stop_name") REFERENCES "stop" ("stop_name");

ALTER TABLE "route_step" ADD FOREIGN KEY ("route_name") REFERENCES "route" ("route_name");

ALTER TABLE "route_step" ADD FOREIGN KEY ("stop_name") REFERENCES "stop" ("stop_name");

ALTER TABLE "bus_schedule" ADD FOREIGN KEY ("bus_id") REFERENCES "bus" ("bus_id");

ALTER TABLE "bus_schedule" ADD FOREIGN KEY ("route_name") REFERENCES "route" ("route_name");

ALTER TABLE "bus_schedule" ADD FOREIGN KEY ("driver_id") REFERENCES "driver" ("driver_id");

ALTER TABLE "user_table" ADD FOREIGN KEY ("role_id") REFERENCES "user_role" ("role_id");

ALTER TABLE "event_helper" ADD FOREIGN KEY ("bus_id") REFERENCES "bus" ("bus_id");

ALTER TABLE "chat_message" ADD FOREIGN KEY ("from") REFERENCES "user_table" ("email");

ALTER TABLE "chat_room" ADD FOREIGN KEY ("email") REFERENCES "user_table" ("email");

ALTER TABLE "event_helper" ADD FOREIGN KEY ("email") REFERENCES "user_table" ("email");

ALTER TABLE "swap_request" ADD FOREIGN KEY ("from") REFERENCES "user_table" ("email");

ALTER TABLE "swap_request" ADD FOREIGN KEY ("with") REFERENCES "user_table" ("email");

ALTER TABLE "chat_room" ADD FOREIGN KEY ("room_id") REFERENCES "room_name" ("room_id");

ALTER TABLE "past_passwords" ADD FOREIGN KEY ("email") REFERENCES "user_table" ("email");
